// Code generated by protoc-gen-go. DO NOT EDIT.
// source: installer.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type File struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Content              []byte   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_675879a591bd3155, []int{0}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *File) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type TypeMeta struct {
	Kind                 string   `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	ApiVersion           string   `protobuf:"bytes,2,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TypeMeta) Reset()         { *m = TypeMeta{} }
func (m *TypeMeta) String() string { return proto.CompactTextString(m) }
func (*TypeMeta) ProtoMessage()    {}
func (*TypeMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_675879a591bd3155, []int{1}
}

func (m *TypeMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TypeMeta.Unmarshal(m, b)
}
func (m *TypeMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TypeMeta.Marshal(b, m, deterministic)
}
func (m *TypeMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TypeMeta.Merge(m, src)
}
func (m *TypeMeta) XXX_Size() int {
	return xxx_messageInfo_TypeMeta.Size(m)
}
func (m *TypeMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_TypeMeta.DiscardUnknown(m)
}

var xxx_messageInfo_TypeMeta proto.InternalMessageInfo

func (m *TypeMeta) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *TypeMeta) GetApiVersion() string {
	if m != nil {
		return m.ApiVersion
	}
	return ""
}

// ObjectMeta is metadata that all persisted resources must have, which includes all objects
// users must create.
type ObjectMeta struct {
	Name                       string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	GenerateName               string            `protobuf:"bytes,2,opt,name=generateName,proto3" json:"generateName,omitempty"`
	Namespace                  string            `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	SelfLink                   string            `protobuf:"bytes,4,opt,name=selfLink,proto3" json:"selfLink,omitempty"`
	Uid                        string            `protobuf:"bytes,5,opt,name=uid,proto3" json:"uid,omitempty"`
	ResourceVersion            string            `protobuf:"bytes,6,opt,name=resourceVersion,proto3" json:"resourceVersion,omitempty"`
	Generation                 int64             `protobuf:"varint,7,opt,name=generation,proto3" json:"generation,omitempty"`
	CreationTimestamp          *Time             `protobuf:"bytes,8,opt,name=creationTimestamp,proto3" json:"creationTimestamp,omitempty"`
	DeletionTimestamp          *Time             `protobuf:"bytes,9,opt,name=deletionTimestamp,proto3" json:"deletionTimestamp,omitempty"`
	DeletionGracePeriodSeconds int64             `protobuf:"varint,10,opt,name=deletionGracePeriodSeconds,proto3" json:"deletionGracePeriodSeconds,omitempty"`
	Labels                     map[string]string `protobuf:"bytes,11,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Annotations                map[string]string `protobuf:"bytes,12,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	OwnerReferences            []*OwnerReference `protobuf:"bytes,13,rep,name=ownerReferences,proto3" json:"ownerReferences,omitempty"`
	// +patchStrategy=merge
	Finalizers           []string              `protobuf:"bytes,14,rep,name=finalizers,proto3" json:"finalizers,omitempty"`
	ClusterName          string                `protobuf:"bytes,15,opt,name=clusterName,proto3" json:"clusterName,omitempty"`
	ManagedFields        []*ManagedFieldsEntry `protobuf:"bytes,17,rep,name=managedFields,proto3" json:"managedFields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ObjectMeta) Reset()         { *m = ObjectMeta{} }
func (m *ObjectMeta) String() string { return proto.CompactTextString(m) }
func (*ObjectMeta) ProtoMessage()    {}
func (*ObjectMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_675879a591bd3155, []int{2}
}

func (m *ObjectMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectMeta.Unmarshal(m, b)
}
func (m *ObjectMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectMeta.Marshal(b, m, deterministic)
}
func (m *ObjectMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectMeta.Merge(m, src)
}
func (m *ObjectMeta) XXX_Size() int {
	return xxx_messageInfo_ObjectMeta.Size(m)
}
func (m *ObjectMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectMeta.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectMeta proto.InternalMessageInfo

func (m *ObjectMeta) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ObjectMeta) GetGenerateName() string {
	if m != nil {
		return m.GenerateName
	}
	return ""
}

func (m *ObjectMeta) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ObjectMeta) GetSelfLink() string {
	if m != nil {
		return m.SelfLink
	}
	return ""
}

func (m *ObjectMeta) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ObjectMeta) GetResourceVersion() string {
	if m != nil {
		return m.ResourceVersion
	}
	return ""
}

func (m *ObjectMeta) GetGeneration() int64 {
	if m != nil {
		return m.Generation
	}
	return 0
}

func (m *ObjectMeta) GetCreationTimestamp() *Time {
	if m != nil {
		return m.CreationTimestamp
	}
	return nil
}

func (m *ObjectMeta) GetDeletionTimestamp() *Time {
	if m != nil {
		return m.DeletionTimestamp
	}
	return nil
}

func (m *ObjectMeta) GetDeletionGracePeriodSeconds() int64 {
	if m != nil {
		return m.DeletionGracePeriodSeconds
	}
	return 0
}

func (m *ObjectMeta) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *ObjectMeta) GetAnnotations() map[string]string {
	if m != nil {
		return m.Annotations
	}
	return nil
}

func (m *ObjectMeta) GetOwnerReferences() []*OwnerReference {
	if m != nil {
		return m.OwnerReferences
	}
	return nil
}

func (m *ObjectMeta) GetFinalizers() []string {
	if m != nil {
		return m.Finalizers
	}
	return nil
}

func (m *ObjectMeta) GetClusterName() string {
	if m != nil {
		return m.ClusterName
	}
	return ""
}

func (m *ObjectMeta) GetManagedFields() []*ManagedFieldsEntry {
	if m != nil {
		return m.ManagedFields
	}
	return nil
}

// OwnerReference contains enough information to let you identify an owning
// object. An owning object must be in the same namespace as the dependent, or
// be cluster-scoped, so there is no namespace field.
type OwnerReference struct {
	// API version of the referent.
	ApiVersion string `protobuf:"bytes,5,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	// Kind of the referent.
	// More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// Name of the referent.
	// More info: http://kubernetes.io/docs/user-guide/identifiers#names
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// UID of the referent.
	// More info: http://kubernetes.io/docs/user-guide/identifiers#uids
	Uid string `protobuf:"bytes,4,opt,name=uid,proto3" json:"uid,omitempty"`
	// If true, this reference points to the managing controller.
	// +
	Controller bool `protobuf:"varint,6,opt,name=controller,proto3" json:"controller,omitempty"`
	// If true, AND if the owner has the "foregroundDeletion" finalizer, then
	// the owner cannot be deleted from the key-value store until this
	// reference is removed.
	// Defaults to false.
	// To set this field, a user needs "delete" permission of the owner,
	// otherwise 422 (Unprocessable Entity) will be returned.
	// +
	BlockOwnerDeletion   bool     `protobuf:"varint,7,opt,name=blockOwnerDeletion,proto3" json:"blockOwnerDeletion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OwnerReference) Reset()         { *m = OwnerReference{} }
func (m *OwnerReference) String() string { return proto.CompactTextString(m) }
func (*OwnerReference) ProtoMessage()    {}
func (*OwnerReference) Descriptor() ([]byte, []int) {
	return fileDescriptor_675879a591bd3155, []int{3}
}

func (m *OwnerReference) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OwnerReference.Unmarshal(m, b)
}
func (m *OwnerReference) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OwnerReference.Marshal(b, m, deterministic)
}
func (m *OwnerReference) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OwnerReference.Merge(m, src)
}
func (m *OwnerReference) XXX_Size() int {
	return xxx_messageInfo_OwnerReference.Size(m)
}
func (m *OwnerReference) XXX_DiscardUnknown() {
	xxx_messageInfo_OwnerReference.DiscardUnknown(m)
}

var xxx_messageInfo_OwnerReference proto.InternalMessageInfo

func (m *OwnerReference) GetApiVersion() string {
	if m != nil {
		return m.ApiVersion
	}
	return ""
}

func (m *OwnerReference) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *OwnerReference) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OwnerReference) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *OwnerReference) GetController() bool {
	if m != nil {
		return m.Controller
	}
	return false
}

func (m *OwnerReference) GetBlockOwnerDeletion() bool {
	if m != nil {
		return m.BlockOwnerDeletion
	}
	return false
}

// ManagedFieldsEntry is a workflow-id, a FieldSet and the group version of the resource
// that the fieldset applies to.
type ManagedFieldsEntry struct {
	// Manager is an identifier of the workflow managing these fields.
	Manager string `protobuf:"bytes,1,opt,name=manager,proto3" json:"manager,omitempty"`
	// Operation is the type of operation which lead to this ManagedFieldsEntry being created.
	// The only valid values for this field are 'Apply' and 'Update'.
	Operation string `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	// APIVersion defines the version of this resource that this field set
	// applies to. The format is "group/version" just like the top-level
	// APIVersion field. It is necessary to track the version of a field
	// set because it cannot be automatically converted.
	ApiVersion string `protobuf:"bytes,3,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	// Time is timestamp of when these fields were set. It should always be empty if Operation is 'Apply'
	// +
	Time *Time `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	// Fields identifies a set of fields.
	// +
	Fields               *Fields  `protobuf:"bytes,5,opt,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ManagedFieldsEntry) Reset()         { *m = ManagedFieldsEntry{} }
func (m *ManagedFieldsEntry) String() string { return proto.CompactTextString(m) }
func (*ManagedFieldsEntry) ProtoMessage()    {}
func (*ManagedFieldsEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_675879a591bd3155, []int{4}
}

func (m *ManagedFieldsEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManagedFieldsEntry.Unmarshal(m, b)
}
func (m *ManagedFieldsEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManagedFieldsEntry.Marshal(b, m, deterministic)
}
func (m *ManagedFieldsEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManagedFieldsEntry.Merge(m, src)
}
func (m *ManagedFieldsEntry) XXX_Size() int {
	return xxx_messageInfo_ManagedFieldsEntry.Size(m)
}
func (m *ManagedFieldsEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_ManagedFieldsEntry.DiscardUnknown(m)
}

var xxx_messageInfo_ManagedFieldsEntry proto.InternalMessageInfo

func (m *ManagedFieldsEntry) GetManager() string {
	if m != nil {
		return m.Manager
	}
	return ""
}

func (m *ManagedFieldsEntry) GetOperation() string {
	if m != nil {
		return m.Operation
	}
	return ""
}

func (m *ManagedFieldsEntry) GetApiVersion() string {
	if m != nil {
		return m.ApiVersion
	}
	return ""
}

func (m *ManagedFieldsEntry) GetTime() *Time {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *ManagedFieldsEntry) GetFields() *Fields {
	if m != nil {
		return m.Fields
	}
	return nil
}

// Time is a wrapper around time.Time which supports correct
// marshaling to YAML and JSON.  Wrappers are provided for many
// of the factory methods that the time package offers.
//
// +protobuf.options.marshal=false
// +protobuf.as=Timestamp
// +protobuf.options.(gogoproto.goproto_stringer)=false
type Time struct {
	// Represents seconds of UTC time since Unix epoch
	// 1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to
	// 9999-12-31T23:59:59Z inclusive.
	Seconds int64 `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	// Non-negative fractions of a second at nanosecond resolution. Negative
	// second values with fractions must still have non-negative nanos values
	// that count forward in time. Must be from 0 to 999,999,999
	// inclusive. This field may be limited in precision depending on context.
	Nanos                int32    `protobuf:"varint,2,opt,name=nanos,proto3" json:"nanos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Time) Reset()         { *m = Time{} }
func (m *Time) String() string { return proto.CompactTextString(m) }
func (*Time) ProtoMessage()    {}
func (*Time) Descriptor() ([]byte, []int) {
	return fileDescriptor_675879a591bd3155, []int{5}
}

func (m *Time) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Time.Unmarshal(m, b)
}
func (m *Time) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Time.Marshal(b, m, deterministic)
}
func (m *Time) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Time.Merge(m, src)
}
func (m *Time) XXX_Size() int {
	return xxx_messageInfo_Time.Size(m)
}
func (m *Time) XXX_DiscardUnknown() {
	xxx_messageInfo_Time.DiscardUnknown(m)
}

var xxx_messageInfo_Time proto.InternalMessageInfo

func (m *Time) GetSeconds() int64 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

func (m *Time) GetNanos() int32 {
	if m != nil {
		return m.Nanos
	}
	return 0
}

// Fields stores a set of fields in a data structure like a Trie.
// To understand how this is used, see: https://github.com/kubernetes-sigs/structured-merge-diff
type Fields struct {
	// Map stores a set of fields in a data structure like a Trie.
	//
	// Each key is either a '.' representing the field itself, and will always map to an empty set,
	// or a string representing a sub-field or item. The string will follow one of these four formats:
	// 'f:<name>', where <name> is the name of a field in a struct, or key in a map
	// 'v:<value>', where <value> is the exact json formatted value of a list item
	// 'i:<index>', where <index> is position of a item in a list
	// 'k:<keys>', where <keys> is a map of  a list item's key fields to their unique values
	// If a key maps to an empty Fields value, the field that key represents is part of the set.
	//
	// The exact format is defined in k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/internal
	Map                  map[string]*Fields `protobuf:"bytes,1,rep,name=map,proto3" json:"map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Fields) Reset()         { *m = Fields{} }
func (m *Fields) String() string { return proto.CompactTextString(m) }
func (*Fields) ProtoMessage()    {}
func (*Fields) Descriptor() ([]byte, []int) {
	return fileDescriptor_675879a591bd3155, []int{6}
}

func (m *Fields) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Fields.Unmarshal(m, b)
}
func (m *Fields) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Fields.Marshal(b, m, deterministic)
}
func (m *Fields) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fields.Merge(m, src)
}
func (m *Fields) XXX_Size() int {
	return xxx_messageInfo_Fields.Size(m)
}
func (m *Fields) XXX_DiscardUnknown() {
	xxx_messageInfo_Fields.DiscardUnknown(m)
}

var xxx_messageInfo_Fields proto.InternalMessageInfo

func (m *Fields) GetMap() map[string]*Fields {
	if m != nil {
		return m.Map
	}
	return nil
}

type KubernetesClusterSpec struct {
	Cluster              *Cluster `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Addons               *Addons  `protobuf:"bytes,2,opt,name=addons,proto3" json:"addons,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KubernetesClusterSpec) Reset()         { *m = KubernetesClusterSpec{} }
func (m *KubernetesClusterSpec) String() string { return proto.CompactTextString(m) }
func (*KubernetesClusterSpec) ProtoMessage()    {}
func (*KubernetesClusterSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_675879a591bd3155, []int{7}
}

func (m *KubernetesClusterSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KubernetesClusterSpec.Unmarshal(m, b)
}
func (m *KubernetesClusterSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KubernetesClusterSpec.Marshal(b, m, deterministic)
}
func (m *KubernetesClusterSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KubernetesClusterSpec.Merge(m, src)
}
func (m *KubernetesClusterSpec) XXX_Size() int {
	return xxx_messageInfo_KubernetesClusterSpec.Size(m)
}
func (m *KubernetesClusterSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_KubernetesClusterSpec.DiscardUnknown(m)
}

var xxx_messageInfo_KubernetesClusterSpec proto.InternalMessageInfo

func (m *KubernetesClusterSpec) GetCluster() *Cluster {
	if m != nil {
		return m.Cluster
	}
	return nil
}

func (m *KubernetesClusterSpec) GetAddons() *Addons {
	if m != nil {
		return m.Addons
	}
	return nil
}

type Cluster struct {
	TimeoutMins          string      `protobuf:"bytes,1,opt,name=timeoutMins,proto3" json:"timeoutMins,omitempty"`
	ClusterType          string      `protobuf:"bytes,2,opt,name=clusterType,proto3" json:"clusterType,omitempty"`
	PodCIDR              string      `protobuf:"bytes,3,opt,name=podCIDR,proto3" json:"podCIDR,omitempty"`
	ServiceCIDR          string      `protobuf:"bytes,4,opt,name=serviceCIDR,proto3" json:"serviceCIDR,omitempty"`
	MasterList           []*Node     `protobuf:"bytes,5,rep,name=masterList,proto3" json:"masterList,omitempty"`
	ExternalLoadBalancer string      `protobuf:"bytes,6,opt,name=externalLoadBalancer,proto3" json:"externalLoadBalancer,omitempty"`
	NodeList             []*Node     `protobuf:"bytes,7,rep,name=nodeList,proto3" json:"nodeList,omitempty"`
	EtcdList             []*Node     `protobuf:"bytes,8,rep,name=etcdList,proto3" json:"etcdList,omitempty"`
	Region               string      `protobuf:"bytes,9,opt,name=region,proto3" json:"region,omitempty"`
	AuthConfig           *AuthConfig `protobuf:"bytes,10,opt,name=authConfig,proto3" json:"authConfig,omitempty"`
	KubeVersion          string      `protobuf:"bytes,11,opt,name=kubeVersion,proto3" json:"kubeVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Cluster) Reset()         { *m = Cluster{} }
func (m *Cluster) String() string { return proto.CompactTextString(m) }
func (*Cluster) ProtoMessage()    {}
func (*Cluster) Descriptor() ([]byte, []int) {
	return fileDescriptor_675879a591bd3155, []int{8}
}

func (m *Cluster) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cluster.Unmarshal(m, b)
}
func (m *Cluster) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cluster.Marshal(b, m, deterministic)
}
func (m *Cluster) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cluster.Merge(m, src)
}
func (m *Cluster) XXX_Size() int {
	return xxx_messageInfo_Cluster.Size(m)
}
func (m *Cluster) XXX_DiscardUnknown() {
	xxx_messageInfo_Cluster.DiscardUnknown(m)
}

var xxx_messageInfo_Cluster proto.InternalMessageInfo

func (m *Cluster) GetTimeoutMins() string {
	if m != nil {
		return m.TimeoutMins
	}
	return ""
}

func (m *Cluster) GetClusterType() string {
	if m != nil {
		return m.ClusterType
	}
	return ""
}

func (m *Cluster) GetPodCIDR() string {
	if m != nil {
		return m.PodCIDR
	}
	return ""
}

func (m *Cluster) GetServiceCIDR() string {
	if m != nil {
		return m.ServiceCIDR
	}
	return ""
}

func (m *Cluster) GetMasterList() []*Node {
	if m != nil {
		return m.MasterList
	}
	return nil
}

func (m *Cluster) GetExternalLoadBalancer() string {
	if m != nil {
		return m.ExternalLoadBalancer
	}
	return ""
}

func (m *Cluster) GetNodeList() []*Node {
	if m != nil {
		return m.NodeList
	}
	return nil
}

func (m *Cluster) GetEtcdList() []*Node {
	if m != nil {
		return m.EtcdList
	}
	return nil
}

func (m *Cluster) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *Cluster) GetAuthConfig() *AuthConfig {
	if m != nil {
		return m.AuthConfig
	}
	return nil
}

func (m *Cluster) GetKubeVersion() string {
	if m != nil {
		return m.KubeVersion
	}
	return ""
}

type Addons struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Addons) Reset()         { *m = Addons{} }
func (m *Addons) String() string { return proto.CompactTextString(m) }
func (*Addons) ProtoMessage()    {}
func (*Addons) Descriptor() ([]byte, []int) {
	return fileDescriptor_675879a591bd3155, []int{9}
}

func (m *Addons) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Addons.Unmarshal(m, b)
}
func (m *Addons) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Addons.Marshal(b, m, deterministic)
}
func (m *Addons) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Addons.Merge(m, src)
}
func (m *Addons) XXX_Size() int {
	return xxx_messageInfo_Addons.Size(m)
}
func (m *Addons) XXX_DiscardUnknown() {
	xxx_messageInfo_Addons.DiscardUnknown(m)
}

var xxx_messageInfo_Addons proto.InternalMessageInfo

type Node struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_675879a591bd3155, []int{10}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type AuthConfig struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	PrivateSSHKey        string   `protobuf:"bytes,3,opt,name=privateSSHKey,proto3" json:"privateSSHKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthConfig) Reset()         { *m = AuthConfig{} }
func (m *AuthConfig) String() string { return proto.CompactTextString(m) }
func (*AuthConfig) ProtoMessage()    {}
func (*AuthConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_675879a591bd3155, []int{11}
}

func (m *AuthConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthConfig.Unmarshal(m, b)
}
func (m *AuthConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthConfig.Marshal(b, m, deterministic)
}
func (m *AuthConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthConfig.Merge(m, src)
}
func (m *AuthConfig) XXX_Size() int {
	return xxx_messageInfo_AuthConfig.Size(m)
}
func (m *AuthConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthConfig.DiscardUnknown(m)
}

var xxx_messageInfo_AuthConfig proto.InternalMessageInfo

func (m *AuthConfig) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AuthConfig) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AuthConfig) GetPrivateSSHKey() string {
	if m != nil {
		return m.PrivateSSHKey
	}
	return ""
}

type KubernetesClusterRequest struct {
	TypeMeta             *TypeMeta              `protobuf:"bytes,1,opt,name=typeMeta,proto3" json:"typeMeta,omitempty"`
	ObjectMeta           *ObjectMeta            `protobuf:"bytes,2,opt,name=objectMeta,proto3" json:"objectMeta,omitempty"`
	Spec                 *KubernetesClusterSpec `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *KubernetesClusterRequest) Reset()         { *m = KubernetesClusterRequest{} }
func (m *KubernetesClusterRequest) String() string { return proto.CompactTextString(m) }
func (*KubernetesClusterRequest) ProtoMessage()    {}
func (*KubernetesClusterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_675879a591bd3155, []int{12}
}

func (m *KubernetesClusterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KubernetesClusterRequest.Unmarshal(m, b)
}
func (m *KubernetesClusterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KubernetesClusterRequest.Marshal(b, m, deterministic)
}
func (m *KubernetesClusterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KubernetesClusterRequest.Merge(m, src)
}
func (m *KubernetesClusterRequest) XXX_Size() int {
	return xxx_messageInfo_KubernetesClusterRequest.Size(m)
}
func (m *KubernetesClusterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KubernetesClusterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KubernetesClusterRequest proto.InternalMessageInfo

func (m *KubernetesClusterRequest) GetTypeMeta() *TypeMeta {
	if m != nil {
		return m.TypeMeta
	}
	return nil
}

func (m *KubernetesClusterRequest) GetObjectMeta() *ObjectMeta {
	if m != nil {
		return m.ObjectMeta
	}
	return nil
}

func (m *KubernetesClusterRequest) GetSpec() *KubernetesClusterSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

type InstallClusterResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstallClusterResponse) Reset()         { *m = InstallClusterResponse{} }
func (m *InstallClusterResponse) String() string { return proto.CompactTextString(m) }
func (*InstallClusterResponse) ProtoMessage()    {}
func (*InstallClusterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_675879a591bd3155, []int{13}
}

func (m *InstallClusterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstallClusterResponse.Unmarshal(m, b)
}
func (m *InstallClusterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstallClusterResponse.Marshal(b, m, deterministic)
}
func (m *InstallClusterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstallClusterResponse.Merge(m, src)
}
func (m *InstallClusterResponse) XXX_Size() int {
	return xxx_messageInfo_InstallClusterResponse.Size(m)
}
func (m *InstallClusterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InstallClusterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InstallClusterResponse proto.InternalMessageInfo

func (m *InstallClusterResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*File)(nil), "v1.File")
	proto.RegisterType((*TypeMeta)(nil), "v1.TypeMeta")
	proto.RegisterType((*ObjectMeta)(nil), "v1.ObjectMeta")
	proto.RegisterMapType((map[string]string)(nil), "v1.ObjectMeta.AnnotationsEntry")
	proto.RegisterMapType((map[string]string)(nil), "v1.ObjectMeta.LabelsEntry")
	proto.RegisterType((*OwnerReference)(nil), "v1.OwnerReference")
	proto.RegisterType((*ManagedFieldsEntry)(nil), "v1.ManagedFieldsEntry")
	proto.RegisterType((*Time)(nil), "v1.Time")
	proto.RegisterType((*Fields)(nil), "v1.Fields")
	proto.RegisterMapType((map[string]*Fields)(nil), "v1.Fields.MapEntry")
	proto.RegisterType((*KubernetesClusterSpec)(nil), "v1.KubernetesClusterSpec")
	proto.RegisterType((*Cluster)(nil), "v1.Cluster")
	proto.RegisterType((*Addons)(nil), "v1.Addons")
	proto.RegisterType((*Node)(nil), "v1.Node")
	proto.RegisterType((*AuthConfig)(nil), "v1.AuthConfig")
	proto.RegisterType((*KubernetesClusterRequest)(nil), "v1.KubernetesClusterRequest")
	proto.RegisterType((*InstallClusterResponse)(nil), "v1.InstallClusterResponse")
}

func init() { proto.RegisterFile("installer.proto", fileDescriptor_675879a591bd3155) }

var fileDescriptor_675879a591bd3155 = []byte{
	// 1106 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0xcb, 0x6e, 0x1b, 0x37,
	0x17, 0xfe, 0x47, 0x37, 0x8f, 0x8e, 0x1c, 0x39, 0xe1, 0xef, 0x1a, 0x53, 0xc1, 0x48, 0x85, 0x41,
	0x02, 0x08, 0x05, 0x2a, 0xd7, 0x6a, 0x11, 0xb4, 0x41, 0x60, 0xc0, 0x71, 0x9a, 0xd6, 0x88, 0x9d,
	0x16, 0x74, 0xd0, 0x3d, 0x35, 0x73, 0xa4, 0x32, 0x1e, 0x91, 0x53, 0x92, 0x52, 0xea, 0x2e, 0xfb,
	0x0a, 0x5d, 0x74, 0xd5, 0x55, 0xf7, 0x7d, 0x80, 0xbc, 0x46, 0x5f, 0xa1, 0x0f, 0x52, 0x90, 0xc3,
	0x91, 0x46, 0x17, 0x14, 0xe8, 0x8e, 0xfc, 0xce, 0x85, 0x67, 0xce, 0xf9, 0xbe, 0x21, 0xe1, 0x80,
	0x0b, 0x6d, 0x58, 0x96, 0xa1, 0x1a, 0xe6, 0x4a, 0x1a, 0x49, 0x6a, 0x8b, 0xd3, 0xde, 0xf1, 0x54,
	0xca, 0x69, 0x86, 0x27, 0x2c, 0xe7, 0x27, 0x4c, 0x08, 0x69, 0x98, 0xe1, 0x52, 0xe8, 0xc2, 0x23,
	0xfe, 0x1c, 0x1a, 0x2f, 0x79, 0x86, 0x84, 0x40, 0x43, 0xb0, 0x19, 0x46, 0x41, 0x3f, 0x18, 0xb4,
	0xa9, 0x5b, 0x93, 0x08, 0xf6, 0x12, 0x29, 0x0c, 0x0a, 0x13, 0xd5, 0xfa, 0xc1, 0x60, 0x9f, 0x96,
	0xdb, 0xf8, 0x0c, 0xc2, 0x37, 0x77, 0x39, 0x5e, 0xa3, 0x61, 0x36, 0xf2, 0x96, 0x8b, 0xb4, 0x8c,
	0xb4, 0x6b, 0xf2, 0x10, 0x80, 0xe5, 0xfc, 0x7b, 0x54, 0x9a, 0x4b, 0xe1, 0x82, 0xdb, 0xb4, 0x82,
	0xc4, 0xef, 0x5b, 0x00, 0xdf, 0x8e, 0xdf, 0x62, 0x62, 0xca, 0x14, 0x5b, 0x87, 0xc7, 0xb0, 0x3f,
	0x45, 0x81, 0x8a, 0x19, 0x7c, 0x6d, 0x6d, 0x45, 0x92, 0x35, 0x8c, 0x1c, 0x43, 0xdb, 0xfa, 0xea,
	0x9c, 0x25, 0x18, 0xd5, 0x9d, 0xc3, 0x0a, 0x20, 0x3d, 0x08, 0x35, 0x66, 0x93, 0x2b, 0x2e, 0x6e,
	0xa3, 0x86, 0x33, 0x2e, 0xf7, 0xe4, 0x3e, 0xd4, 0xe7, 0x3c, 0x8d, 0x9a, 0x0e, 0xb6, 0x4b, 0x32,
	0x80, 0x03, 0x85, 0x5a, 0xce, 0x55, 0x82, 0x65, 0xdd, 0x2d, 0x67, 0xdd, 0x84, 0xed, 0xc7, 0xf9,
	0x2a, 0xac, 0xd3, 0x5e, 0x3f, 0x18, 0xd4, 0x69, 0x05, 0x21, 0x4f, 0xe0, 0x41, 0xa2, 0xd0, 0xad,
	0xdf, 0xf0, 0x19, 0x6a, 0xc3, 0x66, 0x79, 0x14, 0xf6, 0x83, 0x41, 0x67, 0x14, 0x0e, 0x17, 0xa7,
	0x43, 0x0b, 0xd2, 0x6d, 0x17, 0x1b, 0x97, 0x62, 0x86, 0xeb, 0x71, 0xed, 0xcd, 0xb8, 0x2d, 0x17,
	0x72, 0x06, 0xbd, 0x12, 0xfc, 0x5a, 0xb1, 0x04, 0xbf, 0x43, 0xc5, 0x65, 0x7a, 0x83, 0x89, 0x14,
	0xa9, 0x8e, 0xc0, 0xd5, 0xf7, 0x2f, 0x1e, 0x64, 0x04, 0xad, 0x8c, 0x8d, 0x31, 0xd3, 0x51, 0xa7,
	0x5f, 0x1f, 0x74, 0x46, 0x3d, 0x7b, 0xd8, 0x6a, 0x3a, 0xc3, 0x2b, 0x67, 0xfc, 0x4a, 0x18, 0x75,
	0x47, 0xbd, 0x27, 0x39, 0x87, 0x4e, 0x85, 0x4b, 0xd1, 0xbe, 0x0b, 0xfc, 0x68, 0x23, 0xf0, 0x7c,
	0xe5, 0x51, 0x44, 0x57, 0x63, 0xc8, 0x33, 0x38, 0x90, 0xef, 0x04, 0x2a, 0x8a, 0x13, 0x54, 0x28,
	0x12, 0xd4, 0xd1, 0x3d, 0x97, 0x86, 0xb8, 0x34, 0x6b, 0x26, 0xba, 0xe9, 0x6a, 0x87, 0x30, 0xe1,
	0x82, 0x65, 0xfc, 0x67, 0x54, 0x3a, 0xea, 0xf6, 0xeb, 0x96, 0x61, 0x2b, 0x84, 0xf4, 0xa1, 0x93,
	0x64, 0x73, 0x6d, 0x50, 0x39, 0xf6, 0x1c, 0xb8, 0x51, 0x56, 0x21, 0xf2, 0x0c, 0xee, 0xcd, 0x98,
	0x60, 0x53, 0x4c, 0x5f, 0x72, 0xcc, 0x52, 0x1d, 0x3d, 0x70, 0xa7, 0x1f, 0xd9, 0xd3, 0xaf, 0xab,
	0x86, 0xa2, 0xf6, 0x75, 0xe7, 0xde, 0x97, 0xd0, 0xa9, 0xf4, 0xc5, 0xf2, 0xe9, 0x16, 0xef, 0x3c,
	0x81, 0xed, 0x92, 0x1c, 0x42, 0x73, 0xc1, 0xb2, 0x79, 0x49, 0xdc, 0x62, 0xf3, 0xb4, 0xf6, 0x45,
	0xd0, 0x3b, 0x83, 0xfb, 0x9b, 0x9d, 0xf9, 0x2f, 0xf1, 0xf1, 0xfb, 0x00, 0xba, 0xeb, 0xed, 0xd9,
	0xd0, 0x5b, 0x73, 0x53, 0x6f, 0x3b, 0x35, 0x5a, 0x8a, 0xae, 0x5e, 0x11, 0x9d, 0x97, 0x45, 0x63,
	0x25, 0x8b, 0x87, 0x00, 0x56, 0xf4, 0x4a, 0xda, 0xbf, 0x8a, 0x53, 0x44, 0x48, 0x2b, 0x08, 0x19,
	0x02, 0x19, 0x67, 0x32, 0xb9, 0x75, 0x05, 0xbd, 0xf0, 0x24, 0x73, 0xa2, 0x08, 0xe9, 0x0e, 0x4b,
	0xfc, 0x67, 0x00, 0x64, 0xbb, 0xbb, 0xf6, 0x57, 0x53, 0xf4, 0x57, 0xf9, 0x1a, 0xcb, 0xad, 0xd5,
	0xb8, 0xcc, 0x4b, 0xb1, 0x15, 0xbd, 0x58, 0x01, 0x1b, 0x1f, 0x5e, 0xdf, 0xfa, 0xf0, 0x63, 0x68,
	0x18, 0x3e, 0x43, 0xf7, 0x45, 0x55, 0x19, 0x39, 0x94, 0xc4, 0xd0, 0x9a, 0x14, 0xb3, 0x6f, 0x3a,
	0x3b, 0x58, 0x7b, 0x51, 0x16, 0xf5, 0x96, 0xf8, 0x09, 0x34, 0x6c, 0x84, 0xad, 0x50, 0x7b, 0x49,
	0x05, 0x4e, 0x52, 0xe5, 0xd6, 0x4e, 0x4a, 0x30, 0x21, 0xb5, 0xab, 0xae, 0x49, 0x8b, 0x4d, 0xac,
	0xa1, 0x55, 0x64, 0x22, 0x8f, 0xa1, 0x3e, 0x63, 0x79, 0x14, 0x38, 0x7a, 0xfd, 0x7f, 0x75, 0xc4,
	0xf0, 0x9a, 0xe5, 0x05, 0xb7, 0xac, 0xbd, 0xf7, 0x1c, 0xc2, 0x12, 0xd8, 0x41, 0x87, 0x7e, 0x95,
	0x0e, 0xeb, 0x95, 0x56, 0xa8, 0x31, 0x86, 0x0f, 0x5e, 0xcd, 0xc7, 0xa8, 0x04, 0x1a, 0xd4, 0x17,
	0x05, 0xd9, 0x6f, 0x72, 0x4c, 0xc8, 0x63, 0xd8, 0xf3, 0xdc, 0x77, 0x49, 0x3b, 0xa3, 0x8e, 0x4d,
	0xe0, 0x3d, 0x68, 0x69, 0xb3, 0x0d, 0x61, 0x69, 0x6a, 0x15, 0x5d, 0x39, 0xe6, 0xdc, 0x21, 0xd4,
	0x5b, 0xe2, 0xdf, 0xeb, 0xb0, 0xe7, 0x03, 0xad, 0xca, 0x6c, 0x23, 0xe5, 0xdc, 0x5c, 0x73, 0xa1,
	0x7d, 0xbd, 0x55, 0xa8, 0xa2, 0x43, 0x7b, 0x61, 0xf8, 0x01, 0x56, 0x21, 0xdb, 0xd8, 0x5c, 0xa6,
	0x17, 0x97, 0x2f, 0xa8, 0x9f, 0x5f, 0xb9, 0xb5, 0xb1, 0x1a, 0xd5, 0x82, 0x27, 0xe8, 0xac, 0x05,
	0x2b, 0xab, 0x10, 0x19, 0x00, 0xcc, 0x98, 0xcd, 0x74, 0xc5, 0xb5, 0x89, 0x9a, 0xae, 0xc3, 0x6e,
	0xc8, 0xaf, 0x65, 0x8a, 0xb4, 0x62, 0x23, 0x23, 0x38, 0xc4, 0x9f, 0x0c, 0x2a, 0xc1, 0xb2, 0x2b,
	0xc9, 0xd2, 0xe7, 0x2c, 0x63, 0x22, 0xf1, 0x8c, 0x6e, 0xd3, 0x9d, 0x36, 0xf2, 0x08, 0x42, 0x21,
	0x53, 0x74, 0xb9, 0xf7, 0x36, 0x72, 0x2f, 0x2d, 0xd6, 0x0b, 0x4d, 0x92, 0x3a, 0xaf, 0x70, 0xd3,
	0xab, 0xb4, 0x90, 0x23, 0x68, 0x29, 0x9c, 0x5a, 0x92, 0xb6, 0xdd, 0x89, 0x7e, 0x47, 0x86, 0x00,
	0x6c, 0x6e, 0x7e, 0xb8, 0x90, 0x62, 0xc2, 0xa7, 0xee, 0x67, 0xdd, 0x19, 0x75, 0x5d, 0xd7, 0x97,
	0x28, 0xad, 0x78, 0xd8, 0x9e, 0xdc, 0xce, 0xc7, 0xcb, 0x2b, 0xaa, 0x53, 0xf4, 0xa4, 0x02, 0xc5,
	0x21, 0xb4, 0x8a, 0x89, 0xc5, 0x47, 0xd0, 0xb0, 0x55, 0x90, 0x2e, 0xd4, 0x78, 0xee, 0x87, 0x53,
	0xe3, 0x79, 0xfc, 0x16, 0x60, 0x95, 0xdd, 0x5e, 0x93, 0x73, 0x6d, 0x3f, 0x7e, 0x79, 0x01, 0x2f,
	0xf7, 0xd6, 0x96, 0x33, 0xad, 0xdf, 0x49, 0x95, 0xfa, 0xd1, 0x2d, 0xf7, 0xe4, 0x11, 0xdc, 0xcb,
	0x15, 0x5f, 0x30, 0x83, 0x37, 0x37, 0xdf, 0xbc, 0xc2, 0x3b, 0x3f, 0xbd, 0x75, 0x30, 0xfe, 0x23,
	0x80, 0x68, 0x8b, 0x92, 0x14, 0x7f, 0x9c, 0xa3, 0x36, 0x64, 0x00, 0xa1, 0xf1, 0xcf, 0x08, 0x4f,
	0xcb, 0x7d, 0xa7, 0x50, 0x8f, 0xd1, 0xa5, 0xd5, 0xb6, 0x49, 0x2e, 0x2f, 0x16, 0x4f, 0xce, 0xee,
	0xfa, 0x75, 0x43, 0x2b, 0x1e, 0xe4, 0x13, 0x68, 0xe8, 0x1c, 0x13, 0x57, 0x53, 0x67, 0xf4, 0xa1,
	0xf5, 0xdc, 0x29, 0x0c, 0xea, 0xdc, 0xe2, 0x11, 0x1c, 0x5d, 0x16, 0x4f, 0xa7, 0x65, 0x85, 0x3a,
	0x97, 0x42, 0x3b, 0x76, 0xde, 0xcc, 0x93, 0x04, 0x75, 0xc1, 0xee, 0x90, 0x96, 0xdb, 0xd1, 0x6f,
	0x01, 0xb4, 0x2f, 0xcb, 0xf7, 0x16, 0x89, 0x21, 0xbc, 0x90, 0xf9, 0x9d, 0x7b, 0x4b, 0x85, 0x85,
	0x38, 0x33, 0xec, 0x2d, 0x57, 0xf1, 0xff, 0x3e, 0x0d, 0xc8, 0x04, 0xba, 0xeb, 0xa7, 0x90, 0xe3,
	0x9d, 0x85, 0xf9, 0xf6, 0xf4, 0xdc, 0x45, 0xbc, 0xbb, 0xae, 0xb8, 0xf7, 0xcb, 0x5f, 0x7f, 0xff,
	0x5a, 0x3b, 0x8c, 0x0f, 0xdc, 0xbb, 0x6e, 0x71, 0x7a, 0xe2, 0x25, 0xf5, 0x34, 0xf8, 0x78, 0xdc,
	0x72, 0x4f, 0xbb, 0xcf, 0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0x4a, 0x73, 0x74, 0xc1, 0x0f, 0x0a,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// InstallerClient is the client API for Installer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InstallerClient interface {
	// copy file
	CopyFile(ctx context.Context, in *File, opts ...grpc.CallOption) (Installer_CopyFileClient, error)
	// dispatch cluster config to all agent
	InstallCluster(ctx context.Context, in *KubernetesClusterRequest, opts ...grpc.CallOption) (*InstallClusterResponse, error)
}

type installerClient struct {
	cc *grpc.ClientConn
}

func NewInstallerClient(cc *grpc.ClientConn) InstallerClient {
	return &installerClient{cc}
}

func (c *installerClient) CopyFile(ctx context.Context, in *File, opts ...grpc.CallOption) (Installer_CopyFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Installer_serviceDesc.Streams[0], "/v1.Installer/CopyFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &installerCopyFileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Installer_CopyFileClient interface {
	Recv() (*File, error)
	grpc.ClientStream
}

type installerCopyFileClient struct {
	grpc.ClientStream
}

func (x *installerCopyFileClient) Recv() (*File, error) {
	m := new(File)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *installerClient) InstallCluster(ctx context.Context, in *KubernetesClusterRequest, opts ...grpc.CallOption) (*InstallClusterResponse, error) {
	out := new(InstallClusterResponse)
	err := c.cc.Invoke(ctx, "/v1.Installer/InstallCluster", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InstallerServer is the server API for Installer service.
type InstallerServer interface {
	// copy file
	CopyFile(*File, Installer_CopyFileServer) error
	// dispatch cluster config to all agent
	InstallCluster(context.Context, *KubernetesClusterRequest) (*InstallClusterResponse, error)
}

// UnimplementedInstallerServer can be embedded to have forward compatible implementations.
type UnimplementedInstallerServer struct {
}

func (*UnimplementedInstallerServer) CopyFile(req *File, srv Installer_CopyFileServer) error {
	return status.Errorf(codes.Unimplemented, "method CopyFile not implemented")
}
func (*UnimplementedInstallerServer) InstallCluster(ctx context.Context, req *KubernetesClusterRequest) (*InstallClusterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InstallCluster not implemented")
}

func RegisterInstallerServer(s *grpc.Server, srv InstallerServer) {
	s.RegisterService(&_Installer_serviceDesc, srv)
}

func _Installer_CopyFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(File)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InstallerServer).CopyFile(m, &installerCopyFileServer{stream})
}

type Installer_CopyFileServer interface {
	Send(*File) error
	grpc.ServerStream
}

type installerCopyFileServer struct {
	grpc.ServerStream
}

func (x *installerCopyFileServer) Send(m *File) error {
	return x.ServerStream.SendMsg(m)
}

func _Installer_InstallCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KubernetesClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstallerServer).InstallCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Installer/InstallCluster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstallerServer).InstallCluster(ctx, req.(*KubernetesClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Installer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.Installer",
	HandlerType: (*InstallerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InstallCluster",
			Handler:    _Installer_InstallCluster_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CopyFile",
			Handler:       _Installer_CopyFile_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "installer.proto",
}
