# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: installer.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("installer.proto", :syntax => :proto3) do
    add_message "v1.File" do
      optional :name, :string, 1
      optional :content, :bytes, 2
    end
    add_message "v1.TypeMeta" do
      optional :kind, :string, 1
      optional :apiVersion, :string, 2
    end
    add_message "v1.ObjectMeta" do
      optional :name, :string, 1
      optional :generateName, :string, 2
      optional :namespace, :string, 3
      optional :selfLink, :string, 4
      optional :uid, :string, 5
      optional :resourceVersion, :string, 6
      optional :generation, :int64, 7
      optional :creationTimestamp, :message, 8, "v1.Time"
      optional :deletionTimestamp, :message, 9, "v1.Time"
      optional :deletionGracePeriodSeconds, :int64, 10
      map :labels, :string, :string, 11
      map :annotations, :string, :string, 12
      repeated :ownerReferences, :message, 13, "v1.OwnerReference"
      repeated :finalizers, :string, 14
      optional :clusterName, :string, 15
      repeated :managedFields, :message, 17, "v1.ManagedFieldsEntry"
    end
    add_message "v1.OwnerReference" do
      optional :apiVersion, :string, 5
      optional :kind, :string, 1
      optional :name, :string, 3
      optional :uid, :string, 4
      optional :controller, :bool, 6
      optional :blockOwnerDeletion, :bool, 7
    end
    add_message "v1.ManagedFieldsEntry" do
      optional :manager, :string, 1
      optional :operation, :string, 2
      optional :apiVersion, :string, 3
      optional :time, :message, 4, "v1.Time"
      optional :fields, :message, 5, "v1.Fields"
    end
    add_message "v1.Time" do
      optional :seconds, :int64, 1
      optional :nanos, :int32, 2
    end
    add_message "v1.Fields" do
      map :map, :string, :message, 1, "v1.Fields"
    end
    add_message "v1.KubernetesClusterSpec" do
      optional :cluster, :message, 1, "v1.Cluster"
      optional :addons, :message, 2, "v1.Addons"
    end
    add_message "v1.Cluster" do
      optional :timeoutMins, :string, 1
      optional :clusterType, :string, 2
      optional :podCIDR, :string, 3
      optional :serviceCIDR, :string, 4
      repeated :masterList, :message, 5, "v1.Node"
      optional :externalLoadBalancer, :string, 6
      repeated :nodeList, :message, 7, "v1.Node"
      repeated :etcdList, :message, 8, "v1.Node"
      optional :region, :string, 9
      optional :authConfig, :message, 10, "v1.AuthConfig"
      optional :kubeVersion, :string, 11
    end
    add_message "v1.Addons" do
    end
    add_message "v1.Node" do
      optional :ip, :string, 1
    end
    add_message "v1.AuthConfig" do
      optional :username, :string, 1
      optional :password, :string, 2
      optional :privateSSHKey, :string, 3
    end
    add_message "v1.KubernetesClusterRequest" do
      optional :typeMeta, :message, 1, "v1.TypeMeta"
      optional :objectMeta, :message, 2, "v1.ObjectMeta"
      optional :spec, :message, 3, "v1.KubernetesClusterSpec"
    end
    add_message "v1.InstallClusterResponse" do
      optional :Success, :bool, 1
    end
  end
end

module V1
  File = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.File").msgclass
  TypeMeta = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.TypeMeta").msgclass
  ObjectMeta = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.ObjectMeta").msgclass
  OwnerReference = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.OwnerReference").msgclass
  ManagedFieldsEntry = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.ManagedFieldsEntry").msgclass
  Time = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.Time").msgclass
  Fields = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.Fields").msgclass
  KubernetesClusterSpec = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.KubernetesClusterSpec").msgclass
  Cluster = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.Cluster").msgclass
  Addons = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.Addons").msgclass
  Node = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.Node").msgclass
  AuthConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.AuthConfig").msgclass
  KubernetesClusterRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.KubernetesClusterRequest").msgclass
  InstallClusterResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.InstallClusterResponse").msgclass
end
